home:
    path: /
    defaults: {_controller: AppBundle:Default:index}
login:
    path:     /login
    defaults: { _controller: AppBundle:User:login }

sign_in:
    path:     /signin
    defaults: { _controller: AppBundle:User:signIn }
