<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getActiveByEmail($email)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.email = :email AND u.status = 1')
            ->setParameter('email', $email)
            ->getQuery();
        return $query->getOneOrNullResult();
    }

    public function getActiveById($id)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.id = :userid AND u.status = 1')
            ->setParameter('userid', (int)$id)
            ->getQuery();
        return $query->getOneOrNullResult();
    }
}
